// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/builtin_options.dart';
import 'api/engine.dart';
import 'api/eval_options.dart';
import 'api/hello.dart';
import 'api/js_error.dart';
import 'api/js_value.dart';
import 'api/module.dart';
import 'api/repl.dart';
import 'api/runtime.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class JsRuntimeLibApiImplPlatform
    extends BaseApiImpl<JsRuntimeLibWire> {
  JsRuntimeLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JsReplPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsReplPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  JsRepl
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          dynamic raw);

  @protected
  JsRepl
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          dynamic raw);

  @protected
  JsRepl
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          dynamic raw);

  @protected
  FutureOr<String> Function(String)
      dco_decode_DartFn_Inputs_String_Output_String_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  JsRepl
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  JsBuiltinOptions dco_decode_box_autoadd_js_builtin_options(dynamic raw);

  @protected
  JsEngine dco_decode_box_autoadd_js_engine(dynamic raw);

  @protected
  JsError dco_decode_box_autoadd_js_error(dynamic raw);

  @protected
  JsEvalOptions dco_decode_box_autoadd_js_eval_options(dynamic raw);

  @protected
  JsModule dco_decode_box_autoadd_js_module(dynamic raw);

  @protected
  JsRuntime dco_decode_box_autoadd_js_runtime(dynamic raw);

  @protected
  JsRuntimeOptions dco_decode_box_autoadd_js_runtime_options(dynamic raw);

  @protected
  JsValue dco_decode_box_autoadd_js_value(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  JsValue dco_decode_box_js_value(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  JsBuiltinOptions dco_decode_js_builtin_options(dynamic raw);

  @protected
  JsEngine dco_decode_js_engine(dynamic raw);

  @protected
  JsError dco_decode_js_error(dynamic raw);

  @protected
  JsEvalOptions dco_decode_js_eval_options(dynamic raw);

  @protected
  JsModule dco_decode_js_module(dynamic raw);

  @protected
  JsRuntime dco_decode_js_runtime(dynamic raw);

  @protected
  JsRuntimeOptions dco_decode_js_runtime_options(dynamic raw);

  @protected
  JsValue dco_decode_js_value(dynamic raw);

  @protected
  List<JsValue> dco_decode_list_box_js_value(dynamic raw);

  @protected
  List<JsModule> dco_decode_list_js_module(dynamic raw);

  @protected
  List<JsValue> dco_decode_list_js_value(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, JsValue)> dco_decode_list_record_string_box_js_value(
      dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  JsBuiltinOptions? dco_decode_opt_box_autoadd_js_builtin_options(dynamic raw);

  @protected
  JsEvalOptions? dco_decode_opt_box_autoadd_js_eval_options(dynamic raw);

  @protected
  JsRuntimeOptions? dco_decode_opt_box_autoadd_js_runtime_options(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<JsModule>? dco_decode_opt_list_js_module(dynamic raw);

  @protected
  (String, JsValue) dco_decode_record_string_box_js_value(dynamic raw);

  @protected
  ReplResult dco_decode_repl_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  JsRepl
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          SseDeserializer deserializer);

  @protected
  JsRepl
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          SseDeserializer deserializer);

  @protected
  JsRepl
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  JsRepl
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JsBuiltinOptions sse_decode_box_autoadd_js_builtin_options(
      SseDeserializer deserializer);

  @protected
  JsEngine sse_decode_box_autoadd_js_engine(SseDeserializer deserializer);

  @protected
  JsError sse_decode_box_autoadd_js_error(SseDeserializer deserializer);

  @protected
  JsEvalOptions sse_decode_box_autoadd_js_eval_options(
      SseDeserializer deserializer);

  @protected
  JsModule sse_decode_box_autoadd_js_module(SseDeserializer deserializer);

  @protected
  JsRuntime sse_decode_box_autoadd_js_runtime(SseDeserializer deserializer);

  @protected
  JsRuntimeOptions sse_decode_box_autoadd_js_runtime_options(
      SseDeserializer deserializer);

  @protected
  JsValue sse_decode_box_autoadd_js_value(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  JsValue sse_decode_box_js_value(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  JsBuiltinOptions sse_decode_js_builtin_options(SseDeserializer deserializer);

  @protected
  JsEngine sse_decode_js_engine(SseDeserializer deserializer);

  @protected
  JsError sse_decode_js_error(SseDeserializer deserializer);

  @protected
  JsEvalOptions sse_decode_js_eval_options(SseDeserializer deserializer);

  @protected
  JsModule sse_decode_js_module(SseDeserializer deserializer);

  @protected
  JsRuntime sse_decode_js_runtime(SseDeserializer deserializer);

  @protected
  JsRuntimeOptions sse_decode_js_runtime_options(SseDeserializer deserializer);

  @protected
  JsValue sse_decode_js_value(SseDeserializer deserializer);

  @protected
  List<JsValue> sse_decode_list_box_js_value(SseDeserializer deserializer);

  @protected
  List<JsModule> sse_decode_list_js_module(SseDeserializer deserializer);

  @protected
  List<JsValue> sse_decode_list_js_value(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, JsValue)> sse_decode_list_record_string_box_js_value(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JsBuiltinOptions? sse_decode_opt_box_autoadd_js_builtin_options(
      SseDeserializer deserializer);

  @protected
  JsEvalOptions? sse_decode_opt_box_autoadd_js_eval_options(
      SseDeserializer deserializer);

  @protected
  JsRuntimeOptions? sse_decode_opt_box_autoadd_js_runtime_options(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<JsModule>? sse_decode_opt_list_js_module(SseDeserializer deserializer);

  @protected
  (String, JsValue) sse_decode_record_string_box_js_value(
      SseDeserializer deserializer);

  @protected
  ReplResult sse_decode_repl_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          JsRepl self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          JsRepl self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          JsRepl self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_String_Output_String_AnyhowException(
      FutureOr<String> Function(String) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
          JsRepl self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_builtin_options(
      JsBuiltinOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_engine(
      JsEngine self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_error(JsError self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_eval_options(
      JsEvalOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_module(
      JsModule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_runtime(
      JsRuntime self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_runtime_options(
      JsRuntimeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_value(JsValue self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_js_value(JsValue self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_js_builtin_options(
      JsBuiltinOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_engine(JsEngine self, SseSerializer serializer);

  @protected
  void sse_encode_js_error(JsError self, SseSerializer serializer);

  @protected
  void sse_encode_js_eval_options(JsEvalOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_module(JsModule self, SseSerializer serializer);

  @protected
  void sse_encode_js_runtime(JsRuntime self, SseSerializer serializer);

  @protected
  void sse_encode_js_runtime_options(
      JsRuntimeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_value(JsValue self, SseSerializer serializer);

  @protected
  void sse_encode_list_box_js_value(
      List<JsValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_js_module(List<JsModule> self, SseSerializer serializer);

  @protected
  void sse_encode_list_js_value(List<JsValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_box_js_value(
      List<(String, JsValue)> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_builtin_options(
      JsBuiltinOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_eval_options(
      JsEvalOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_runtime_options(
      JsRuntimeOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_js_module(
      List<JsModule>? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_box_js_value(
      (String, JsValue) self, SseSerializer serializer);

  @protected
  void sse_encode_repl_result(ReplResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class JsRuntimeLibWire implements BaseWire {
  factory JsRuntimeLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      JsRuntimeLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  JsRuntimeLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsReplPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_js_runtime_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsReplPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsReplPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_js_runtime_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRepl =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsReplPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
