// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_process_memory`, `next_id`, `register_web_apis`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RuntimeState`

/// JS 运行时句柄。通过 [JsRuntime::create] 创建，使用完毕后调用 [JsRuntime::dispose] 释放。
class JsRuntime {
  final BigInt id;

  const JsRuntime({
    required this.id,
  });

  /// 创建一个新的 JS 运行时，返回句柄。
  ///
  /// # 参数
  /// - `max_memory_bytes`: 可选的内存上限（字节），`null` 或 `0` 表示不限制。
  ///   超出上限后 [eval_js](Self::eval_js) 会返回错误。
  ///
  /// 使用完毕后必须调用 [dispose](Self::dispose) 释放资源。
  static JsRuntime create({BigInt? maxMemoryBytes}) => RustLib.instance.api
      .crateApiBoaJsRuntimeCreate(maxMemoryBytes: maxMemoryBytes);

  /// 销毁运行时，释放其占用的所有资源。
  ///
  /// 调用后该句柄不再可用。
  void dispose() => RustLib.instance.api.crateApiBoaJsRuntimeDispose(
        that: this,
      );

  /// 执行 JavaScript 代码，返回求值结果的字符串表示。
  ///
  /// 如已设置 `max_memory_bytes`，执行后若估算内存超过上限则返回错误。
  String evalJs({required String code}) =>
      RustLib.instance.api.crateApiBoaJsRuntimeEvalJs(that: this, code: code);

  /// 获取当前运行时的**估算内存用量**（字节）。
  ///
  /// 估算值 = 已执行代码总字节数 + 已加载模块源码总字节数。
  /// 包含该运行时创建以来所有 `eval_js` 和 `preload_module` 调用的累计值。
  BigInt memoryUsage() => RustLib.instance.api.crateApiBoaJsRuntimeMemoryUsage(
        that: this,
      );

  /// 预加载一个 ES 模块，使其可通过 `import('name')` 动态导入。
  void preloadModule({required String name, required String source}) =>
      RustLib.instance.api.crateApiBoaJsRuntimePreloadModule(
          that: this, name: name, source: source);

  /// 释放内存 —— 清理当前运行时中由 `WeakRef` 保持的对象。
  ///
  /// 调用后内存用量可能下降。若需完全重置内存，建议 `dispose()` 后重新 `create()`。
  void releaseMemory() =>
      RustLib.instance.api.crateApiBoaJsRuntimeReleaseMemory(
        that: this,
      );

  /// 获取**所有运行时所在进程的物理内存**用量（字节）。
  ///
  /// - Linux / HarmonyOS: 读取 `/proc/self/status` 的 RSS（常驻集大小）。
  /// - 其他平台: 返回 `0`（不支持）。
  ///
  /// 该值反映的是整个进程的内存占用，而非单个运行时。
  static BigInt totalMemoryUsage() =>
      RustLib.instance.api.crateApiBoaJsRuntimeTotalMemoryUsage();

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsRuntime && runtimeType == other.runtimeType && id == other.id;
}
