// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'js_value.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `as_array`, `as_bigint`, `as_bytes`, `as_object`, `as_string`, `as_symbol`, `build_js_array_literal`, `build_js_object_literal`, `from_boa`, `into_boa`, `is_valid_js_identifier`, `js_value_to_literal`, `to_boa`

@freezed
sealed class JsValue with _$JsValue {
  const JsValue._();

  /// `null` 或 `undefined`
  const factory JsValue.none() = JsValue_None;

  /// 布尔值
  const factory JsValue.boolean(
    bool field0,
  ) = JsValue_Boolean;

  /// 整数（i64，兼容 Dart int）
  const factory JsValue.integer(
    PlatformInt64 field0,
  ) = JsValue_Integer;

  /// 浮点数
  const factory JsValue.float(
    double field0,
  ) = JsValue_Float;

  /// BigInt，以字符串形式表示（含后缀 `n`，如 `"9007199254740993n"`）
  const factory JsValue.bigInt(
    String field0,
  ) = JsValue_BigInt;

  /// 字符串
  const factory JsValue.string(
    String field0,
  ) = JsValue_String_;

  /// 二进制数据
  const factory JsValue.bytes(
    Uint8List field0,
  ) = JsValue_Bytes;

  /// 数组
  const factory JsValue.array(
    List<JsValue> field0,
  ) = JsValue_Array;

  /// 对象（键值对列表，FRB 兼容）。Dart 端可转为 `Map<String, JsValue>`。
  const factory JsValue.object(
    List<(String, JsValue)> field0,
  ) = JsValue_Object;

  /// Date，Unix 毫秒时间戳
  const factory JsValue.date(
    PlatformInt64 field0,
  ) = JsValue_Date;

  /// Symbol，描述字符串
  const factory JsValue.symbol(
    String field0,
  ) = JsValue_Symbol;

  Future<bool?> asBoolean() =>
      RustLib.instance.api.crateApiJsValueJsValueAsBoolean(
        that: this,
      );

  Future<PlatformInt64?> asDate() =>
      RustLib.instance.api.crateApiJsValueJsValueAsDate(
        that: this,
      );

  Future<double?> asFloat() =>
      RustLib.instance.api.crateApiJsValueJsValueAsFloat(
        that: this,
      );

  Future<PlatformInt64?> asInteger() =>
      RustLib.instance.api.crateApiJsValueJsValueAsInteger(
        that: this,
      );

  Future<double?> asNumber() =>
      RustLib.instance.api.crateApiJsValueJsValueAsNumber(
        that: this,
      );

  static Future<JsValue> fromBool({required bool b}) =>
      RustLib.instance.api.crateApiJsValueJsValueFromBool(b: b);

  static Future<JsValue> fromFloat({required double f}) =>
      RustLib.instance.api.crateApiJsValueJsValueFromFloat(f: f);

  static Future<JsValue> fromInt({required PlatformInt64 i}) =>
      RustLib.instance.api.crateApiJsValueJsValueFromInt(i: i);

  static Future<JsValue> fromStr({required String s}) =>
      RustLib.instance.api.crateApiJsValueJsValueFromStr(s: s);

  static Future<JsValue> fromString({required String s}) =>
      RustLib.instance.api.crateApiJsValueJsValueFromString(s: s);

  Future<bool> isArray() => RustLib.instance.api.crateApiJsValueJsValueIsArray(
        that: this,
      );

  Future<bool> isBigint() =>
      RustLib.instance.api.crateApiJsValueJsValueIsBigint(
        that: this,
      );

  Future<bool> isBoolean() =>
      RustLib.instance.api.crateApiJsValueJsValueIsBoolean(
        that: this,
      );

  Future<bool> isBytes() => RustLib.instance.api.crateApiJsValueJsValueIsBytes(
        that: this,
      );

  Future<bool> isDate() => RustLib.instance.api.crateApiJsValueJsValueIsDate(
        that: this,
      );

  Future<bool> isNone() => RustLib.instance.api.crateApiJsValueJsValueIsNone(
        that: this,
      );

  Future<bool> isNumber() =>
      RustLib.instance.api.crateApiJsValueJsValueIsNumber(
        that: this,
      );

  Future<bool> isObject() =>
      RustLib.instance.api.crateApiJsValueJsValueIsObject(
        that: this,
      );

  Future<bool> isPrimitive() =>
      RustLib.instance.api.crateApiJsValueJsValueIsPrimitive(
        that: this,
      );

  Future<bool> isString() =>
      RustLib.instance.api.crateApiJsValueJsValueIsString(
        that: this,
      );

  Future<bool> isSymbol() =>
      RustLib.instance.api.crateApiJsValueJsValueIsSymbol(
        that: this,
      );

  static Future<JsValue> null_() =>
      RustLib.instance.api.crateApiJsValueJsValueNull();

  /// 返回 JS 类型名称（如 `"number"`、`"string"`、`"object"` 等）。
  Future<String> typeName() =>
      RustLib.instance.api.crateApiJsValueJsValueTypeName(
        that: this,
      );
}
