// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'builtin_options.dart';
import 'eval_options.dart';
import 'js_error.dart';
import 'js_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `eval_internal`

/// JS 运行时句柄。
///
/// 通过 [JsRuntime::create] 创建，使用完毕后调用 [JsRuntime::dispose] 释放。
/// 每次调用会占用资源（Boa 上下文），建议复用。
class JsRuntime {
  final BigInt id;

  const JsRuntime({
    required this.id,
  });

  /// 创建一个新的 JS 运行时。
  ///
  /// # 参数
  /// - `options`: 运行时配置选项，`null` 使用默认值（无内存限制 + essential 内置模块）。
  static JsRuntime create({JsRuntimeOptions? options}) =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeCreate(options: options);

  /// 旧版 create 的别名：使用简单的内存限制参数。
  ///
  /// 新代码推荐使用 `JsRuntime::create(options:)`。
  static JsRuntime createLegacy({BigInt? maxMemoryBytes}) =>
      RustLib.instance.api
          .crateApiRuntimeJsRuntimeCreateLegacy(maxMemoryBytes: maxMemoryBytes);

  /// 销毁运行时，释放所有关联资源。
  ///
  /// 调用后该句柄不再可用。
  void dispose() => RustLib.instance.api.crateApiRuntimeJsRuntimeDispose(
        that: this,
      );

  /// 执行 JavaScript 代码，返回类型化的 [JsValue]。
  ///
  /// 自动解析 Promise（通过 `await_blocking`）。
  /// 如已设置内存上限，执行前后会进行内存检查。
  ///
  /// # 错误
  /// - [JsError::Syntax] — 代码解析失败
  /// - [JsError::Runtime] — 执行期间抛出异常
  /// - [JsError::MemoryLimit] — 内存超限
  JsValue eval({required String code}) =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeEval(that: this, code: code);

  /// 旧版 eval_js 的别名：返回字符串而非 [JsValue]。
  ///
  /// 新代码推荐使用 `eval(code)` 获取类型化的 [JsValue]。
  String evalJsStr({required String code}) => RustLib.instance.api
      .crateApiRuntimeJsRuntimeEvalJsStr(that: this, code: code);

  /// 带选项执行 JavaScript 代码。
  ///
  /// `options` 控制 strict mode、global scope 等行为。
  /// 详见 [JsEvalOptions]。
  JsValue evalWithOptions(
          {required String code, required JsEvalOptions options}) =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeEvalWithOptions(
          that: this, code: code, options: options);

  /// 获取当前运行时的估算内存用量（字节）。
  BigInt memoryUsage() =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeMemoryUsage(
        that: this,
      );

  /// 预加载一个 ES 模块，使其可通过 `import('name')` 动态导入。
  void preloadModule({required String name, required String source}) =>
      RustLib.instance.api.crateApiRuntimeJsRuntimePreloadModule(
          that: this, name: name, source: source);

  /// 释放内存 —— 同 [run_gc](Self::run_gc)。
  void releaseMemory() =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeReleaseMemory(
        that: this,
      );

  /// 触发垃圾回收。
  ///
  /// 调用 `boa_gc::force_collect()` 执行完整的标记-清除 GC，
  /// 同时清理 WeakRef 保持的对象。
  void runGc() => RustLib.instance.api.crateApiRuntimeJsRuntimeRunGc(
        that: this,
      );

  /// 设置内存上限（字节），`0` 表示不限制。
  void setMemoryLimit({required BigInt limitBytes}) =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeSetMemoryLimit(
          that: this, limitBytes: limitBytes);

  /// 获取进程的物理内存用量（字节），平台不支持时返回 `0`。
  static BigInt totalMemoryUsage() =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeTotalMemoryUsage();

  /// 校验 JavaScript 代码语法，**不执行代码**。
  ///
  /// 使用 `boa_parser` 解析为 Script AST，成功返回 `Ok(())`，
  /// 失败返回包含行列信息的 [JsError::Syntax]。
  ///
  /// 与 `eval()` 不同，此方法不会创建或修改任何 JS 运行时状态。
  static void validate({required String code}) =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeValidate(code: code);

  /// 校验 ES 模块语法，**不执行代码**。
  ///
  /// 使用 `boa_parser` 解析为 Module AST。
  /// 适用于在 `preload_module()` 之前预检模块源码。
  static void validateModule({required String name, required String source}) =>
      RustLib.instance.api
          .crateApiRuntimeJsRuntimeValidateModule(name: name, source: source);

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsRuntime && runtimeType == other.runtimeType && id == other.id;
}

/// 运行时选项。
class JsRuntimeOptions {
  /// 内存上限（字节），`0` 或 `null` 表示不限制
  final BigInt? memoryLimit;

  /// 运行时标识名称（用于调试）
  final String? info;

  /// 内置模块配置，默认使用 [JsBuiltinOptions::essential]
  final JsBuiltinOptions? builtins;

  const JsRuntimeOptions({
    this.memoryLimit,
    this.info,
    this.builtins,
  });

  static Future<JsRuntimeOptions> default_() =>
      RustLib.instance.api.crateApiRuntimeJsRuntimeOptionsDefault();

  @override
  int get hashCode => memoryLimit.hashCode ^ info.hashCode ^ builtins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsRuntimeOptions &&
          runtimeType == other.runtimeType &&
          memoryLimit == other.memoryLimit &&
          info == other.info &&
          builtins == other.builtins;
}
