// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'builtin_options.dart';
import 'eval_options.dart';
import 'js_error.dart';
import 'js_value.dart';
import 'module.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'runtime.dart';

/// JS→Dart 方法调用请求。
class CompletedCall {
  final BigInt callId;
  final String name;
  final List<JsValue> params;

  const CompletedCall({
    required this.callId,
    required this.name,
    required this.params,
  });

  @override
  int get hashCode => callId.hashCode ^ name.hashCode ^ params.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletedCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          name == other.name &&
          params == other.params;
}

/// 高层 JS 引擎。
///
/// 内部持有一个 JsRuntime（专用后台工作线程），自动管理生命周期。
/// 方法失败时返回 [JsError]。
class JsEngine {
  final BigInt runtimeId;

  const JsEngine({
    required this.runtimeId,
  });

  /// 调用已注册模块的导出函数。
  ///
  /// # 参数
  /// - `module`: 模块名称（已通过 [declare_module](Self::declare_module) 注册）
  /// - `method`: 导出函数名
  /// - `params`: 参数列表
  Future<JsValue> call(
          {required String module,
          required String method,
          required List<JsValue> params}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineCall(
          that: this, module: module, method: method, params: params);

  /// 取消当前正在等待的 eval（或其他长时间操作）。
  ///
  /// 等待中的调用方会立刻收到 [JsError::Cancelled]。
  /// 工作线程中的 JS 执行会继续在后台完成（结果被丢弃），
  /// 取消后可以立即发起新的 eval 调用。
  void cancelEval() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineCancelEval(
        that: this,
      );

  /// 关闭引擎，释放所有资源（含已注册的回调函数和待处理调用）。
  void close() => JsRuntimeLib.instance.api.crateApiEngineJsEngineClose(
        that: this,
      );

  /// 创建 JS 引擎。
  ///
  /// # 参数
  /// - `builtins`: 内置模块配置，默认 [JsBuiltinOptions::essential]
  /// - `modules`: 创建后立即注册的模块列表
  /// - `runtime_options`: 底层运行时选项（内存上限等）
  static JsEngine create(
          {JsBuiltinOptions? builtins,
          List<JsModule>? modules,
          JsRuntimeOptions? runtimeOptions}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineCreate(
          builtins: builtins, modules: modules, runtimeOptions: runtimeOptions);

  /// 注册一个 ES 模块。
  void declareModule({required JsModule module}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineDeclareModule(that: this, module: module);

  /// 批量注册 ES 模块。同一批中的模块名不允许重复。
  void declareModules({required List<JsModule> modules}) =>
      JsRuntimeLib.instance.api
          .crateApiEngineJsEngineDeclareModules(that: this, modules: modules);

  /// 执行 JavaScript 代码，返回类型化的 [JsValue]。
  ///
  /// 实际执行在工作线程中进行，返回 Future，不阻塞 Dart 主 isolate。
  /// 自动解析顶层 Promise。
  Future<JsValue> eval({required String code}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineEval(that: this, code: code);

  /// 从字节数组执行 JS 代码（UTF-8 编码）。
  Future<JsValue> evalBytes(
          {required List<int> bytes, JsEvalOptions? options}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineEvalBytes(
          that: this, bytes: bytes, options: options);

  /// 从文件路径读取 JS 代码并执行（Script 模式）。
  Future<JsValue> evalFile({required String path, JsEvalOptions? options}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineEvalFile(
          that: this, path: path, options: options);

  /// 读取文件作为 ES 模块执行（支持相对路径 import）。
  ///
  /// 文件所在目录设置为模块解析基础路径。
  Future<JsValue> evalPath({required String path, JsEvalOptions? options}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineEvalPath(
          that: this, path: path, options: options);

  /// 执行 JavaScript 代码，**不**自动 resolve 顶层 Promise。
  ///
  /// 适用于 JS 代码中包含 `await registeredMethod()` 的场景，
  /// 避免 `await_blocking` 与回调等待形成死锁。
  /// 调用后需配合 [run_jobs](Self::run_jobs) 执行微任务。
  Future<JsValue> evalRaw({required String code}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineEvalRaw(that: this, code: code);

  /// 带选项执行 JavaScript 代码。
  Future<JsValue> evalWithOptions(
          {required String code, required JsEvalOptions options}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineEvalWithOptions(
          that: this, code: code, options: options);

  BigInt memoryUsage() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineMemoryUsage(
        that: this,
      );

  /// 拉取所有来自 JS 的待处理方法调用（排空队列）。
  List<CompletedCall> pollCalls() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEnginePollCalls(
        that: this,
      );

  /// 拉取所有来自 JS 的**同步**调用请求（排空队列）。
  ///
  /// 返回 `(call_id, method_name, args_json)` 列表。
  /// 处理完后用 [resolve_sync_call] / [reject_sync_call] 回传结果。
  ///
  /// 此方法直接访问全局 sync_bridge，不经过 worker channel，
  /// 因此可在 JS 执行期间**实时**被调用。
  List<SyncCall> pollSyncCalls() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEnginePollSyncCalls(
        that: this,
      );

  /// （内部）注册 Dart 侧 FFI 回调函数指针。
  ///
  /// 直接操作全局 DART_HANDLERS 注册表，无需经过 worker。
  void registerDartHandler({required PlatformInt64 ptr}) =>
      JsRuntimeLib.instance.api
          .crateApiEngineJsEngineRegisterDartHandler(that: this, ptr: ptr);

  /// 注册一个全局可构造函数（JS 端可通过 `await <name>(...args)` 或 `new <name>(...args)` 调用）。
  void registerGlobalCallable({required String name}) =>
      JsRuntimeLib.instance.api
          .crateApiEngineJsEngineRegisterGlobalCallable(that: this, name: name);

  /// 注册一个全局纯函数（不可构造，JS 端通过 `await <name>(...args)` 调用）。
  void registerGlobalFunction({required String name}) =>
      JsRuntimeLib.instance.api
          .crateApiEngineJsEngineRegisterGlobalFunction(that: this, name: name);

  /// 注册一个同步全局函数（JS 调用立刻响应，无 Promise）。
  void registerSyncFunction({required String name}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineRegisterSyncFunction(that: this, name: name);

  /// 回传错误给 JS 端（reject 对应的 Promise）。
  void rejectCall({required BigInt callId, required String error}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineRejectCall(
          that: this, callId: callId, error: error);

  /// 回传错误给阻塞的 worker 线程（通过 sync_bridge）。
  void rejectSyncCall({required BigInt callId, required String error}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineRejectSyncCall(
          that: this, callId: callId, error: error);

  /// 回传成功结果给 JS 端（resolve 对应的 Promise）。
  void resolveCall({required BigInt callId, required JsValue result}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineResolveCall(
          that: this, callId: callId, result: result);

  /// 回传成功结果给阻塞的 worker 线程（通过 sync_bridge）。
  ///
  /// [result_json] 是 Dart handler 返回值的 JSON 序列化字符串。
  void resolveSyncCall({required BigInt callId, required String resultJson}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineResolveSyncCall(
          that: this, callId: callId, resultJson: resultJson);

  /// 触发垃圾回收。
  void runGc() => JsRuntimeLib.instance.api.crateApiEngineJsEngineRunGc(
        that: this,
      );

  /// 执行待处理的微任务（Promise reactions）。
  void runJobs() => JsRuntimeLib.instance.api.crateApiEngineJsEngineRunJobs(
        that: this,
      );

  /// 设置内存上限（字节），`0` 表示不限制。
  void setMemoryLimit({required BigInt limitBytes}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineSetMemoryLimit(that: this, limitBytes: limitBytes);

  @override
  int get hashCode => runtimeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsEngine &&
          runtimeType == other.runtimeType &&
          runtimeId == other.runtimeId;
}

/// JS→Dart 同步调用请求（sync_bridge 模式）。
///
/// 通过 `poll_sync_calls` 获取，处理完后用 `resolve_sync_call` 回传。
class SyncCall {
  final BigInt callId;
  final String name;

  /// JSON 序列化的参数数组
  final String argsJson;

  const SyncCall({
    required this.callId,
    required this.name,
    required this.argsJson,
  });

  @override
  int get hashCode => callId.hashCode ^ name.hashCode ^ argsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          name == other.name &&
          argsJson == other.argsJson;
}
