// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'builtin_options.dart';
import 'eval_options.dart';
import 'js_error.dart';
import 'js_message.dart';
import 'js_value.dart';
import 'module.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'runtime.dart';

// These functions are ignored because they are not marked as `pub`: `runtime`

/// 高层 JS 引擎。
///
/// 内部持有一个 [JsRuntime]，自动管理生命周期。
/// 方法失败时返回 [JsError]。
class JsEngine {
  final BigInt runtimeId;

  const JsEngine({
    required this.runtimeId,
  });

  /// 调用已注册模块的导出函数。
  ///
  /// # 参数
  /// - `module`: 模块名称（已通过 [declare_module](Self::declare_module) 注册）
  /// - `method`: 导出函数名
  /// - `params`: 参数列表
  JsValue call(
          {required String module,
          required String method,
          required List<JsValue> params}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineCall(
          that: this, module: module, method: method, params: params);

  /// 关闭引擎，释放所有资源。
  void close() => JsRuntimeLib.instance.api.crateApiEngineJsEngineClose(
        that: this,
      );

  /// 创建 JS 引擎。
  ///
  /// # 参数
  /// - `builtins`: 内置模块配置，默认 [JsBuiltinOptions::essential]
  /// - `modules`: 创建后立即注册的模块列表
  /// - `runtime_options`: 底层运行时选项（内存上限等）
  static JsEngine create(
          {JsBuiltinOptions? builtins,
          List<JsModule>? modules,
          JsRuntimeOptions? runtimeOptions}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineCreate(
          builtins: builtins, modules: modules, runtimeOptions: runtimeOptions);

  /// 注册一个 ES 模块。
  void declareModule({required JsModule module}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineDeclareModule(that: this, module: module);

  /// 批量注册 ES 模块。同一批中的模块名不允许重复。
  void declareModules({required List<JsModule> modules}) =>
      JsRuntimeLib.instance.api
          .crateApiEngineJsEngineDeclareModules(that: this, modules: modules);

  /// 执行 JavaScript 代码，返回类型化的 [JsValue]。
  JsValue eval({required String code}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineEval(that: this, code: code);

  /// 带选项执行 JavaScript 代码。
  JsValue evalWithOptions(
          {required String code, required JsEvalOptions options}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineEvalWithOptions(
          that: this, code: code, options: options);

  /// 检查是否有来自 JS 的待处理消息（不排空队列）。
  bool hasMessages() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineHasMessages(
        that: this,
      );

  BigInt memoryUsage() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEngineMemoryUsage(
        that: this,
      );

  /// 拉取 JS 端发送的所有消息（排空队列）。
  ///
  /// JS 端通过 `__postMessage(event, data)` 发送消息。
  /// 调用此方法后队列被清空，返回此前积累的所有消息。
  List<JsMessage> pollMessages() =>
      JsRuntimeLib.instance.api.crateApiEngineJsEnginePollMessages(
        that: this,
      );

  /// 从 Dart 发送消息到 JS。
  ///
  /// JS 端需注册处理器：`globalThis.__onDartMessage = (event, data) => { ... }`
  /// 返回 JS 处理器的返回值（如未注册返回 `undefined`）。
  JsValue postMessage({required String event, required JsValue data}) =>
      JsRuntimeLib.instance.api.crateApiEngineJsEnginePostMessage(
          that: this, event: event, data: data);

  /// 触发垃圾回收。
  void runGc() => JsRuntimeLib.instance.api.crateApiEngineJsEngineRunGc(
        that: this,
      );

  /// 设置内存上限（字节），`0` 表示不限制。
  void setMemoryLimit({required BigInt limitBytes}) => JsRuntimeLib.instance.api
      .crateApiEngineJsEngineSetMemoryLimit(that: this, limitBytes: limitBytes);

  @override
  int get hashCode => runtimeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsEngine &&
          runtimeType == other.runtimeType &&
          runtimeId == other.runtimeId;
}
