// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'js_error.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `classify_error`, `parse_syntax_location`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`, `from`, `from`, `from`

@freezed
sealed class JsError with _$JsError implements FrbException {
  const JsError._();

  /// 语法错误（解析失败），包含行列信息。
  const factory JsError.syntax({
    required String message,
    int? line,
    int? column,
  }) = JsError_Syntax;

  /// 类型错误（如对非函数值调用）。
  const factory JsError.type({
    required String message,
  }) = JsError_Type;

  /// 引用错误（访问未定义变量）。
  const factory JsError.reference({
    required String message,
  }) = JsError_Reference;

  /// 运行时错误（JS 执行期间抛出）。
  const factory JsError.runtime({
    required String message,
  }) = JsError_Runtime;

  /// 内存超限。
  const factory JsError.memoryLimit({
    required String message,
  }) = JsError_MemoryLimit;

  /// 栈溢出（递归过深）。
  const factory JsError.stackOverflow({
    required String message,
  }) = JsError_StackOverflow;

  /// 内部错误（引擎或桥接层问题）。
  const factory JsError.internal({
    required String message,
  }) = JsError_Internal;

  /// 通用错误（兜底）。
  const factory JsError.generic({
    required String message,
  }) = JsError_Generic;

  /// 返回稳定的错误码字符串，用于程序化匹配。
  ///
  /// 各变体错误码：
  /// - `Syntax` → `"SYNTAX"`
  /// - `Type` → `"TYPE"`
  /// - `Reference` → `"REFERENCE"`
  /// - `Runtime` → `"RUNTIME"`
  /// - `MemoryLimit` → `"MEMORY_LIMIT"`
  /// - `StackOverflow` → `"STACK_OVERFLOW"`
  /// - `Internal` → `"INTERNAL"`
  /// - `Generic` → `"GENERIC"`
  Future<String> code() => JsRuntimeLib.instance.api.crateApiJsErrorJsErrorCode(
        that: this,
      );

  /// 判断此错误是否可恢复（可继续使用运行时）。
  Future<bool> isRecoverable() =>
      JsRuntimeLib.instance.api.crateApiJsErrorJsErrorIsRecoverable(
        that: this,
      );
}
