// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'js_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Dart↔JS 双向通信通道中的一条消息。
///
/// - `event`: 事件名称/类型标识，如 `"log"`、`"data"`、`"error"`
/// - `data`: 结构化的负载数据，使用 [JsValue] 表示
class JsMessage {
  final String event;
  final JsValue data;

  const JsMessage({
    required this.event,
    required this.data,
  });

  @override
  int get hashCode => event.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsMessage &&
          runtimeType == other.runtimeType &&
          event == other.event &&
          data == other.data;
}
