// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'js_error.dart';
import 'js_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'runtime.dart';


            // These functions are ignored because they are not marked as `pub`: `needs_continuation`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsRepl>>
                abstract class JsRepl implements RustOpaqueInterface {
                    /// 清空代码缓冲区。
 void  clear();


/// 关闭 REPL 并释放运行时。
 void  close();


/// 创建一个新的 REPL 实例。
///
/// 内部创建一个 [JsRuntime]，支持跨行状态保持。
static JsRepl  create()=>JsRuntimeLib.instance.api.crateApiReplJsReplCreate();


/// 提交一行代码进行评估。
///
/// - 如果当前行是完整语句，返回 `is_complete: true` 并清空缓冲区
/// - 如果当前行不完整（如 `function foo() {` 缺少 `}`），返回 `is_complete: false`
///   并将内容追加到内部缓冲区，等待后续行继续
///
/// # 示例流程
/// ```text
/// > var x = 1;           // is_complete: true
/// > function foo() {     // is_complete: false
/// >   return 42;         // is_complete: false
/// > }                    // is_complete: true, 执行整个函数定义
/// ```
 ReplResult  evalLine({required String line });


/// 强制执行当前缓冲区中的所有代码（即使未闭合）。
 ReplResult  forceEval();


/// 获取当前缓冲区内容（未完成的代码）。
 Future<String>  pendingCode();


/// 运行垃圾回收。
 void  runGc();


/// 获取内部运行时引用，用于直接执行 JS。
 Future<JsRuntime>  runtime();



                    
                }
                

/// 单行求值结果。
class ReplResult  {
                /// 求值结果的字符串表示
final String output;
/// 结果的结构化值（与 `output` 对应）
final JsValue value;
/// 此行是否完整（`false` 表示需要继续输入，如未闭合的大括号）
final bool isComplete;

                const ReplResult({required this.output ,required this.value ,required this.isComplete ,});





        @override
        int get hashCode => output.hashCode^value.hashCode^isComplete.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ReplResult &&
                runtimeType == other.runtimeType
                && output == other.output&& value == other.value&& isComplete == other.isComplete;

            }
            