// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'builtin_options.dart';
import 'eval_options.dart';
import 'js_error.dart';
import 'js_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// JS 运行时句柄。
///
/// 通过 [JsRuntime::create] 创建，使用完毕后调用 [JsRuntime::dispose] 释放。
/// 每次调用会创建一个专用的后台工作线程来执行 JS 代码。
class JsRuntime {
  final BigInt id;

  const JsRuntime({
    required this.id,
  });

  /// 取消当前正在等待的 eval（或其他长时间操作）。
  ///
  /// 等待中的调用方会立刻收到 [JsError::Cancelled]。
  /// 工作线程中的 JS 执行会继续在后台完成（结果被丢弃），
  /// 取消后可以立即发起新的 eval 调用。
  void cancelEval() =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeCancelEval(
        that: this,
      );

  /// 创建一个新的 JS 运行时。
  ///
  /// 内部启动一个专用 OS 线程来运行 Boa Context，
  /// 所有后续操作通过 channel 向该线程发送命令。
  ///
  /// # 参数
  /// - `options`: 运行时配置选项，`null` 使用默认值（无内存限制 + essential 内置模块）。
  static JsRuntime create({JsRuntimeOptions? options}) =>
      JsRuntimeLib.instance.api
          .crateApiRuntimeJsRuntimeCreate(options: options);

  /// 旧版 create 的别名：使用简单的内存限制参数。
  static JsRuntime createLegacy({BigInt? maxMemoryBytes}) =>
      JsRuntimeLib.instance.api
          .crateApiRuntimeJsRuntimeCreateLegacy(maxMemoryBytes: maxMemoryBytes);

  /// 销毁运行时，释放所有关联资源。
  ///
  /// 关闭工作线程并释放 Boa Context。调用后该句柄不再可用。
  void dispose() => JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeDispose(
        that: this,
      );

  /// 执行 JavaScript 代码，返回类型化的 [JsValue]。
  ///
  /// 自动解析 Promise（通过 `await_blocking`）。
  /// 实际执行在工作线程中进行，不阻塞 Dart 主 isolate。
  ///
  /// # 错误
  /// - [JsError::Syntax] — 代码解析失败
  /// - [JsError::Runtime] — 执行期间抛出异常
  /// - [JsError::MemoryLimit] — 内存超限
  Future<JsValue> eval({required String code}) => JsRuntimeLib.instance.api
      .crateApiRuntimeJsRuntimeEval(that: this, code: code);

  /// 从字节数组执行 JS 代码（UTF-8 编码）。
  ///
  /// 将字节按 UTF-8 解码后执行。
  Future<JsValue> evalBytes(
          {required List<int> bytes, JsEvalOptions? options}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeEvalBytes(
          that: this, bytes: bytes, options: options);

  /// 从文件路径读取 JS 代码并执行。
  ///
  /// 读取指定路径的文件内容，按 Script 模式执行。
  /// 实际 I/O 和 eval 均在后台工作线程中进行。
  Future<JsValue> evalFile({required String path, JsEvalOptions? options}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeEvalFile(
          that: this, path: path, options: options);

  /// 旧版 eval_js 的别名：返回字符串而非 [JsValue]。
  Future<String> evalJsStr({required String code}) => JsRuntimeLib.instance.api
      .crateApiRuntimeJsRuntimeEvalJsStr(that: this, code: code);

  /// 读取文件作为 ES 模块执行（支持相对路径 import）。
  ///
  /// 文件所在目录会被设置为模块解析的基础路径（通过 `JS_MODULE_BASE_PATH` 环境变量）。
  /// 如需在 JS 代码中使用 `import` 相对路径，请使用此方法。
  Future<JsValue> evalPath({required String path, JsEvalOptions? options}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeEvalPath(
          that: this, path: path, options: options);

  /// 带选项执行 JavaScript 代码。
  ///
  /// `options` 控制 strict mode、global scope 等行为。
  /// 详见 [JsEvalOptions]。
  Future<JsValue> evalWithOptions(
          {required String code, required JsEvalOptions options}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeEvalWithOptions(
          that: this, code: code, options: options);

  /// 获取当前运行时的估算内存用量（字节）。
  BigInt memoryUsage() =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeMemoryUsage(
        that: this,
      );

  /// 预加载一个 ES 模块，使其可通过 `import('name')` 动态导入。
  void preloadModule({required String name, required String source}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimePreloadModule(
          that: this, name: name, source: source);

  /// 释放内存 —— 同 [run_gc](Self::run_gc)。
  void releaseMemory() =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeReleaseMemory(
        that: this,
      );

  /// 触发垃圾回收。
  ///
  /// 在工作线程中执行完整的标记-清除 GC，同时清理 WeakRef 保持的对象。
  void runGc() => JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeRunGc(
        that: this,
      );

  /// 设置内存上限（字节），`0` 表示不限制。
  void setMemoryLimit({required BigInt limitBytes}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeSetMemoryLimit(
          that: this, limitBytes: limitBytes);

  /// 获取进程的物理内存用量（字节），平台不支持时返回 `0`。
  static BigInt totalMemoryUsage() =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeTotalMemoryUsage();

  /// 校验 JavaScript 代码语法，**不执行代码**。
  ///
  /// 使用 `boa_parser` 解析为 Script AST，成功返回 `Ok(())`，
  /// 失败返回包含行列信息的 [JsError::Syntax]。
  ///
  /// 此方法不需要运行时实例，可直接调用。
  static void validate({required String code}) =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeValidate(code: code);

  /// 校验 ES 模块语法，**不执行代码**。
  static void validateModule({required String name, required String source}) =>
      JsRuntimeLib.instance.api
          .crateApiRuntimeJsRuntimeValidateModule(name: name, source: source);

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsRuntime && runtimeType == other.runtimeType && id == other.id;
}

/// 运行时选项。
class JsRuntimeOptions {
  /// 内存上限（字节），`0` 或 `null` 表示不限制
  final BigInt? memoryLimit;

  /// 运行时标识名称（用于调试）
  final String? info;

  /// 内置模块配置，默认使用 [JsBuiltinOptions::essential]
  final JsBuiltinOptions? builtins;

  const JsRuntimeOptions({
    this.memoryLimit,
    this.info,
    this.builtins,
  });

  static Future<JsRuntimeOptions> default_() =>
      JsRuntimeLib.instance.api.crateApiRuntimeJsRuntimeOptionsDefault();

  @override
  int get hashCode => memoryLimit.hashCode ^ info.hashCode ^ builtins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsRuntimeOptions &&
          runtimeType == other.runtimeType &&
          memoryLimit == other.memoryLimit &&
          info == other.info &&
          builtins == other.builtins;
}
